# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: 'Setup build dependencies'
description: 'Sets up the .NET dependencies of MSBuild, SDK, NuGet'
inputs:
  dotnet-version:
    description: 'What .NET SDK version to use'
    required: true
    default: 6.0.x
  sdk:
    description: 'Setup .NET SDK'
    required: false
    default: 'true'
  msbuild:
    description: 'Setup MSBuild'
    required: false
    default: 'true'
  nuget:
    description: 'Setup NuGet'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Setup dotnet
      if: inputs.sdk == 'true'
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup MSBuild
      if: inputs.msbuild == 'true' && runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      if: inputs.nuget == 'true'
      uses: NuGet/setup-nuget@v1.0.5